name: "cifar10"
data {
  name: "train_full_data"
  file_pattern: "/home/hpc/github/ControlledDropout/deepnet/examples/mnist/train_data_40000.npy"
  size: 40000
  dimensions: 3072
  stats_file: "cifar10_stats.npz"
}
data {
  name: "train_full_labels"
  file_pattern: "/home/hpc/github/ControlledDropout/deepnet/examples/mnist/train_labels_40000.npy"
  size: 40000
  dimensions: 1
  num_labels: 10
  sparse: true
}
data {
  name: "train_data"
  file_pattern: "/home/hpc/github/ControlledDropout/deepnet/examples/mnist/train_data_40000.npy"
  size: 40000
  dimensions: 3072
  stats_file: "cifar10_stats.npz"
}
data {
  name: "train_labels"
  file_pattern: "/home/hpc/github/ControlledDropout/deepnet/examples/mnist/train_labels_40000.npy"
  size: 40000
  dimensions: 1
  num_labels: 10
  sparse: true
}
data {
  name: "validation_data"
  file_pattern: "/home/hpc/github/ControlledDropout/deepnet/examples/mnist/validation_data_10000.npy"
  size: 10000
  dimensions: 3072
  stats_file: "cifar10_stats.npz"
}
data {
  name: "validation_labels"
  file_pattern: "/home/hpc/github/ControlledDropout/deepnet/examples/mnist/validation_labels_10000.npy"
  size: 10000
  dimensions: 1
  num_labels: 10
  sparse: true
}
data {
  name: "test_data"
  file_pattern: "/home/hpc/github/ControlledDropout/deepnet/examples/mnist/test_data.npy"
  size: 10000
  dimensions: 3072
  stats_file: "cifar10_stats.npz"
}
data {
  name: "test_labels"
  file_pattern: "/home/hpc/github/ControlledDropout/deepnet/examples/mnist/test_labels.npy"
  size: 10000
  dimensions: 1
  num_labels: 10
  sparse: true
}
gpu_memory: "8G"
main_memory: "16G"
